- name: Install Ruby and dependencies
  ansible.builtin.package:
    name:
      - ruby
      - ruby-dev
      - build-essential
      - zlib1g-dev
      - libssl-dev
    state: present

- name: Install Bundler via gem
  ansible.builtin.gem:
    name: bundler
    user_install: no
    state: present

- name: Install fluentd via gem
  ansible.builtin.gem:
    name: fluentd
    version: "{{ fluentd_version }}"
    user_install: no
    state: present

- name: Install fluent-plugin-prometheus via gem
  ansible.builtin.gem:
    name: fluent-plugin-prometheus
    user_install: no
    state: present

- name: Create user fluentd
  ansible.builtin.user:
    name: fluentd
    system: yes
    create_home: no
    state: present

- name: Make dir for fluentd conf
  ansible.builtin.file:
    path: /etc/fluentd
    state: directory
    owner: fluentd
    group: fluentd
    mode: '0755'

- name: Make dir for Fluentd logs
  ansible.builtin.file:
    path: /var/log/test
    state: directory
    owner: fluentd
    group: fluentd
    mode: '0755'

- name: Make dir for pos_file
  ansible.builtin.file:
    path: /var/lib/fluentd
    state: directory
    owner: fluentd
    group: fluentd
    mode: '0755'

- name: Add fluentd.conf
  ansible.builtin.template:
    src: fluentd.conf.j2
    dest: /etc/fluentd/fluentd.conf
    owner: fluentd
    group: fluentd
    mode: '0644'

- name: Make systemd unit for fluentd
  ansible.builtin.copy:
    dest: /etc/systemd/system/fluentd.service
    content: |
      [Unit]
      Description=Fluentd Service
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/fluentd -c /etc/fluentd/fluentd.conf
      Restart=always
      User=fluentd
      Group=fluentd

      [Install]
      WantedBy=multi-user.target
  notify: reload systemd

- name: Config validation 
  ansible.builtin.command: fluentd --dry-run -c /etc/fluentd/fluentd.conf
  changed_when: false
  ignore_errors: true
  register: fluentd_validation

- name: Fail if validation fails
  ansible.builtin.fail:
    msg: "Fluentd config validation failed: {{ fluentd_validation.stderr }}"
  when: fluentd_validation.rc != 0

- name: Configure Docker logging driver for Fluentd
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  notify: restart docker

- name: Enable and start fluentd
  ansible.builtin.systemd:
    name: fluentd
    enabled: true
    state: started